### ISSUE TITLE
.NET Core 3.0 support

### ISSUE THREAD

**Issue by lgabriel-mdsol** [mdsol/mauth-client-dotnet#48]
The package `Medidata.MAuth.AspNetCore` does not work in .NET Core version 3.0.

It throws the following error 

```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
  Source=Medidata.MAuth.AspNetCore
  StackTrace:
   at Medidata.MAuth.AspNetCore.MAuthMiddleware.<Invoke>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Medidata.MAuth.AspNetCore.MAuthMiddleware.Invoke(HttpContext context)

```

https://github.com/mdsol/mauth-client-dotnet/blob/develop/src/Medidata.MAuth.AspNetCore/MAuthMiddleware.cs#L42

This line of code needs to updated to context.Request.EnableRewind() -> context.Request.EnableBuffering()
See issue https://github.com/aspnet/AspNetCore/issues/12505

**Comment by lgabriel-mdsol** [comment]
@mdsol/team-51

**Comment by bvillanueva-mdsol** [comment]
Adding @prajon84

**Comment by prajon84** [comment]
Thank you @lgabriel-mdsol . @mdsol/architecture-enablement  team will look into the issue and address it.
